version: "3"

services:
  n8n:
    container_name: "integrator_n8n"
    build:
      context: .
      args:
        N8N_USER_FOLDER: /home/node
        N8N_CONFIG_FILES: /home/node/.n8n/n8n_config.json
    restart: always
    ports:
      - "5678:5678"
    environment:
      - NODE_ENV=develop
      - TZ="Europe/Amsterdam"
    volumes:
      - ./shared:/home/node/.n8n/shared
